### ISSUE TITLE
Does this support Jenkins 2.69 ?

### ISSUE THREAD

**Issue by artemus717** [yunlzheng/rancher-plugin#1]
![741bcf13-8e19-4db5-9f3a-8dc9bc8484e9](https://user-images.githubusercontent.com/16465173/28234930-e36d1704-6937-11e7-9d3a-f18ecd48261e.png)

**Comment by yunlzheng** [comment]
@artemus717 You should add the rancher API credentials to jenkins first, Please check the README.
https://github.com/jenkinsci/rancher-plugin#add-the-rancher-api-key-to-jenkins 
Or make sure the credentials plugin already installed.

**Comment by yunlzheng** [comment]
I just try in my local. I think the issue is because the plugin missing **credentials plugin** dependencies information. Please make sure the credentials plugin is already installed. And I already  release a new version 1.0.1.

or manual download 1.0.1 from https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/rancher/1.0.1/rancher-1.0.1.hpi

**Comment by artemus717** [comment]
1.0.1 fix it.
